name: Deploy site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: npm ci
        # This is due to a bug with optionalDependencies not getting installed,
        # see https://github.com/npm/cli/issues/4828
      # - name: Ensure @rollup/rollup-linux-x64-gnu is installed
      #   run: npm install @rollup/rollup-linux-x64-gnu
      - name: Check linting
        run: npm run lint
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
